image: maven:latest
before_script:

cache:
  paths:
    - target/

stages:
  - build
  - test

Test:
  stage: test
  script:
    - mvn test

Build:
  stage: build
  script:
    - mvn install

code-coverage:
  stage: test
  script:
    - mvn -B verify site
  after_script:
    - cat target/site/jacoco/index.html

Checkstyle:
  stage: test
  script:
    - mvn checkstyle:checkstyle